name: Cache Workflow

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Cache dependencies folder (example: ~/.npm for Node.js)
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.npm          # you can change this to pip cache, maven, etc. based on project
          key: cache-c220062

      - name: prime-cache-c220062
        run: echo "Cache ${{ steps.cache.outputs.cache-hit }}"
